package model;

// Generated 18-feb-2015 17:44:27 by Hibernate Tools 3.4.0.CR1

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	/**
	 *  
	 */
	private static final long serialVersionUID = 1L;
	private int idAnswer;
	private Question question;
	private String text;
	private Boolean isCorrect;

	public Answer() {
	}

	public Answer(int idAnswer) {
		this.idAnswer = idAnswer;
	}

	public Answer(int idAnswer, Question question, String text,
			Boolean isCorrect) {
		this.idAnswer = idAnswer;
		this.question = question;
		this.text = text;
		this.isCorrect = isCorrect;
	}

	public int getIdAnswer() {
		return this.idAnswer;
	}

	public void setIdAnswer(int idAnswer) {
		this.idAnswer = idAnswer;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Boolean getIsCorrect() {
		return this.isCorrect;
	}

	public void setIsCorrect(Boolean isCorrect) {
		this.isCorrect = isCorrect;
	}

}
